### ISSUE TITLE
External links - go through the google "This page wants to go here" page or no?

### ISSUE THREAD

**Issue by HeofHIShirts** [OSMIHelp/osmihelp.org#7]
Some of the links in the OSMI Mental Health in Tech documents go through a Google page that says "This page is attempting to direct you to URI X" and give the reader an opportunity to click through or back, and some of them don't.

Since I don't know what the preferred style is for those documents, I left them basically the way they were in the source documents, which means some of them do and some of them don't, still. 

I'll be happy to run through all three documents and add or subtract the redirection page from all the links involved, but it's probably worth coming to a decision about whether to include the redirection page or not before continuing. Help?

**Comment by funkatron** [comment]
We should not include the redirection. It was a carry-over from the initial Google Docs-authored document.

**Comment by HeofHIShirts** [comment]
Excellent. I'll prepare a PR then with the Google Docs materials scrubbed out. Thanks!
